---
- name: Generate initial etcd cluster configuration
  ansible.builtin.set_fact:
    etcd_initial_cluster: |-
      {% for host in groups['etcd'] -%}
        {{ hostvars[host]['inventory_hostname'] }}=https://{{ hostvars[host]['ansible_host'] }}:{{ etcd_peer_port }}{% if not loop.last %},{% endif %}
      {% endfor -%}
  tags: cluster

- name: Template etcd service file
  ansible.builtin.template:
    src: etcd.service.j2
    dest: "/etc/systemd/system/{{ etcd_service_name }}.service"
    owner: "{{ etcd_user }}"
    group: "{{ etcd_group }}"
    mode: "400"
  tags: cluster

- name: Start etcd
  ansible.builtin.systemd:
    name: "{{ etcd_service_name }}"
    state: restarted
    enabled: true
    daemon_reload: true
  tags: cluster
