- name: Generate private key for CSR
  community.crypto.openssl_privatekey:
    path: "{{ etcd_server_cert_dir }}/cert.key"

- name: Generate CSR for etcd server cert
  community.crypto.openssl_csr_pipe:
    privatekey_path: "{{ etcd_server_cert_dir }}/cert.key"
    common_name: Etcd server
  register: csr

- name: Sign certificate with CA
  community.crypto.x509_certificate_pipe:
    csr_content: "{{ csr.csr }}"
    provider: ownca
    ownca_path: "{{ etcd_cacert_dir }}/ca-cert.pem"
    ownca_privatekey_path: "{{ etcd_cacert_dir }}/ca-cert.key"
    ownca_not_after: +365d
    ownca_not_before: "-1d"
  delegate_to: groups['etcd'][0]
  register: certificate

- name: Write certificate file on server
  ansible.builtin.copy:
    dest: "{{ etcd_server_cert_dir }}/cert.pem"
    content: "{{ certificate.certificate }}"
    owner: "{{ etcd_user }}"
    group: "{{ etcd_group }}"
    mode: '0400'
